# Generated by Django 5.0.4 on 2024-04-21 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('now', '0002_alter_speedcubingresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedcubingresult',
            name='milliseconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speedcubingresult',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speedcubingresult',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TimerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
